name: AovDarksword
options:
  bundleIdPrefix: com.aov.ds
targets:
  AovDarksword:
    type: application
    platform: iOS
    sources: [Source]
    settings:
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
      ARCHS: arm64
      IPHONEOS_DEPLOYMENT_TARGET: 17.0
      CODE_SIGN_ENTITLEMENTS: Source/AovDarksword.entitlements
